import { FeiraCienciasResultado } from "@/components/FeiraCienciasResultado";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import "@/styles/Home.module.css";
import styles from "@/styles/Home.module.css";
import Head from "next/head";

// thanks to: https://dev.to/mursalfk/effortless-data-management-connecting-google-sheets-to-your-reactjs-project-n96

export default function Home() {
  return (
    <div className={styles.nextBody}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className={styles.content}>
        <h1>Resultado - Edição 2024-2025</h1>

        <FeiraCienciasResultado />
      </main>

      <Footer />
    </div>
  );
}
